// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skafetin.Api.Data;

#nullable disable

namespace Skafetin.Api.Migrations
{
    [DbContext(typeof(SkafetinDbContext))]
    [Migration("20260908090428_MissingSchemaChanges")]
    partial class MissingSchemaChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Skafetin.Shared.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "InventoryManager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "LocationResponsible"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("Skafetin.Shared.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.AppUserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppUserId", "AppRoleId");

                    b.HasIndex("AppRoleId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReturnNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByEmployeeId");

                    b.HasIndex("AssignmentStatusId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PreviousAssignmentId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.AssignmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssignmentStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aktivno"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vraćeno"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Premješteno"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Stornirano"
                        });
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentCategoryId");

                    b.HasIndex("EquipmentStatusId");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("\"SerialNumber\" IS NOT NULL");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EquipmentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Računalo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mrežna oprema"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Namještaj"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alat"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Klimatizacija"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Medicinska oprema"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ostalo"
                        });
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCover")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UploadedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UploadedByEmployeeId");

                    b.ToTable("EquipmentMedia");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReplacementForEquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultingEquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentCategoryId");

                    b.HasIndex("ProcessedByEmployeeId");

                    b.HasIndex("ReplacementForEquipmentId");

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("RequestedByEmployeeId");

                    b.HasIndex("ResultingEquipmentId");

                    b.ToTable("EquipmentRequests");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EquipmentStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Na skladištu"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zaduženo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Na servisu"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nedostaje"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Otpisano"
                        });
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChangedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByEmployeeId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("EquipmentStatusHistories");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("InventoryStatusId");

                    b.HasIndex("LocationId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CheckedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpectedEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoundLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDamaged")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsFound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CheckedByEmployeeId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ExpectedEmployeeId");

                    b.HasIndex("ExpectedLocationId");

                    b.HasIndex("FoundLocationId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.InventoryStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InventoryStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nacrt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Otvorena"
                        },
                        new
                        {
                            Id = 3,
                            Name = "U tijeku"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Završena"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zaključana"
                        });
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Zip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ured"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Škola"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zdravstvena ustanova"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Socijalna ustanova"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Skladište"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Terenska lokacija"
                        });
                });

            modelBuilder.Entity("Skafetin.Shared.Models.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zaprimljeno"
                        },
                        new
                        {
                            Id = 2,
                            Name = "U obradi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Odobreno"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Odbijeno"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Realizirano"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zatvoreno"
                        });
                });

            modelBuilder.Entity("Skafetin.Shared.Models.WriteOffRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WriteOffRequestStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ProcessedByEmployeeId");

                    b.HasIndex("RequestedByEmployeeId");

                    b.HasIndex("WriteOffRequestStatusId");

                    b.ToTable("WriteOffRequests");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.WriteOffRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WriteOffRequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zaprimljeno"
                        },
                        new
                        {
                            Id = 2,
                            Name = "U obradi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Odobreno"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Odbijeno"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Provedeno"
                        });
                });

            modelBuilder.Entity("Skafetin.Shared.Models.AppUser", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.AppUserRole", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Assignment", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.Employee", "AssignedByEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.AssignmentStatus", "AssignmentStatus")
                        .WithMany("Assignments")
                        .HasForeignKey("AssignmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Equipment", "Equipment")
                        .WithMany("Assignments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Assignment", "PreviousAssignment")
                        .WithMany()
                        .HasForeignKey("PreviousAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByEmployee");

                    b.Navigation("AssignmentStatus");

                    b.Navigation("Employee");

                    b.Navigation("Equipment");

                    b.Navigation("PreviousAssignment");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Employee", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Equipment", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.EquipmentCategory", "EquipmentCategory")
                        .WithMany("Equipment")
                        .HasForeignKey("EquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.EquipmentStatus", "EquipmentStatus")
                        .WithMany("Equipment")
                        .HasForeignKey("EquipmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Location", "Location")
                        .WithMany("Equipment")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentCategory");

                    b.Navigation("EquipmentStatus");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentMedia", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.Equipment", "Equipment")
                        .WithMany("Media")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Employee", "UploadedByEmployee")
                        .WithMany()
                        .HasForeignKey("UploadedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");

                    b.Navigation("UploadedByEmployee");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentRequest", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.EquipmentCategory", "EquipmentCategory")
                        .WithMany()
                        .HasForeignKey("EquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Employee", "ProcessedByEmployee")
                        .WithMany()
                        .HasForeignKey("ProcessedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.Equipment", "ReplacementForEquipment")
                        .WithMany()
                        .HasForeignKey("ReplacementForEquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.RequestStatus", "RequestStatus")
                        .WithMany("EquipmentRequests")
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Equipment", "ResultingEquipment")
                        .WithMany()
                        .HasForeignKey("ResultingEquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipmentCategory");

                    b.Navigation("ProcessedByEmployee");

                    b.Navigation("ReplacementForEquipment");

                    b.Navigation("RequestStatus");

                    b.Navigation("RequestedByEmployee");

                    b.Navigation("ResultingEquipment");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentStatusHistory", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.Employee", "ChangedByEmployee")
                        .WithMany()
                        .HasForeignKey("ChangedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Location", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.EquipmentStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.Location", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.EquipmentStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByEmployee");

                    b.Navigation("Equipment");

                    b.Navigation("FromLocation");

                    b.Navigation("FromStatus");

                    b.Navigation("ToLocation");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Inventory", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.InventoryStatus", "InventoryStatus")
                        .WithMany("Inventories")
                        .HasForeignKey("InventoryStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Location", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("InventoryStatus");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.InventoryItem", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.Employee", "CheckedByEmployee")
                        .WithMany()
                        .HasForeignKey("CheckedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.Equipment", "Equipment")
                        .WithMany("InventoryItems")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Employee", "ExpectedEmployee")
                        .WithMany()
                        .HasForeignKey("ExpectedEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.Location", "ExpectedLocation")
                        .WithMany()
                        .HasForeignKey("ExpectedLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Location", "FoundLocation")
                        .WithMany()
                        .HasForeignKey("FoundLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.Inventory", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckedByEmployee");

                    b.Navigation("Equipment");

                    b.Navigation("ExpectedEmployee");

                    b.Navigation("ExpectedLocation");

                    b.Navigation("FoundLocation");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Location", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.WriteOffRequest", b =>
                {
                    b.HasOne("Skafetin.Shared.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.Employee", "ProcessedByEmployee")
                        .WithMany()
                        .HasForeignKey("ProcessedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Skafetin.Shared.Models.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skafetin.Shared.Models.WriteOffRequestStatus", "WriteOffRequestStatus")
                        .WithMany("WriteOffRequests")
                        .HasForeignKey("WriteOffRequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ProcessedByEmployee");

                    b.Navigation("RequestedByEmployee");

                    b.Navigation("WriteOffRequestStatus");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.AssignmentStatus", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Employee", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Equipment", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("InventoryItems");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentCategory", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.EquipmentStatus", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.InventoryStatus", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Equipment");

                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.RequestStatus", b =>
                {
                    b.Navigation("EquipmentRequests");
                });

            modelBuilder.Entity("Skafetin.Shared.Models.WriteOffRequestStatus", b =>
                {
                    b.Navigation("WriteOffRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
