// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skafetin.Api.Data;

#nullable disable

namespace Skafetin.Api.Migrations
{
    [DbContext(typeof(SkafetinDbContext))]
    partial class SkafetinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
#pragma warning restore 612, 618
        }
    }
}
